PROG73020-M3-Group10/Models/PropertiesViewModel.cs
using EntityLibrary.Entities;

namespace PROG73020_M3_Group10.Models
{
    public class PropertiesViewModel
    {
        public List<Property>? AllProperties { get; set; }

    }
}

PROG73020-M3-Group10/Controllers/PropertyController.cs
using EntityLibrary.Entities;
using LogicLibrary.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PROG73020_M3_Group10.Models;
using PROG73020_M3_Group10.Services;

namespace PROG73020_M3_Group10.Controllers
{
    public class PropertyController : Controller
    {
        public PropertyController(IPropertyManager propertyManager, PropertyDBContext propertyDBContext)
        {
            _propertyManager = propertyManager;
            _propertyContext = propertyDBContext;
        }

        // Default Route for properties
        [HttpGet("/properties")]
        public IActionResult GetProperties()
        {
            PropertiesViewModel model = new PropertiesViewModel()
            {
                AllProperties = _propertyManager.GetProperties()
            };
            return View(model);
        }


        // Default Route for properties with a Search
        [HttpPost("/properties")]
        public IActionResult GetProperties(string search)
        {
            if (!string.IsNullOrEmpty(search))
            {
                ViewBag.SearchTerm = search;
            }

            PropertiesViewModel model = new PropertiesViewModel
            {
                AllProperties = _propertyManager.GetProperties()
            };

            return View(model);
        }

        // Route for viewing the specific details of a listing (Remember Owners cannot edit from here, they edit from My Listings.)
        [HttpGet("/properties/{id}")]
        public IActionResult PropertyDetails(int id)
        {

            Property property = _propertyManager.GetPropertyById(id);

            if (property == null)
            {
                return NotFound();
            }

            return View(property);
        }

        [Authorize]
        // Default Route for properties
        [HttpGet("/myproperties/")]
        public IActionResult GetMyListings()
        {
            Customer customer = _propertyManager.GetCustomerByName(User.Identity.Name);

            PropertiesViewModel model = new PropertiesViewModel()
            {
                AllProperties = _propertyManager.GetPropertiesByOwner(customer.Id)
            };
            return View(model);
        }

        private IPropertyManager _propertyManager;
        private PropertyDBContext _propertyContext;
    }
}

PROG73020-M3-Group10/Views/Property/GetMyListings.cshtml
@using EntityLibrary.Entities;
@model PropertiesViewModel

@{
    ViewData["Title"] = $"My Properties List";
}

<a class="btn btn-primary" asp-controller="Property" asp-action="AddProperty">Add New Property</a>
<br>

<h2>My Owned Property Listings</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Property Address</th>
            <th>Property City</th>
            <th>Price per Night</th>
            <th>Offer Options</th>
            <th>Property Options</th>
        </tr>
    </thead>
    <tbody>
        <!-- iterate thru our list of Properties-->
        @foreach (Property property in Model.AllProperties)
        {
            <tr>
                <td>@property.Address</td>
                <td>@property.City</td>
                <td>$@property.PricePerNight</td>
                <td>
                    <a class="btn btn-secondary" asp-controller="Property" asp-action="GetPropertyBookings" asp-route-Id="@property.PropertyId">View Bookings</a>
                </td>
                <td>
                    <a class="btn btn-warning" asp-controller="Property" asp-action="GetEditProperty" asp-route-id="@property.PropertyId">Edit</a>
                    <a class="btn btn-danger" asp-controller="Property" asp-action="GetDeleteProperty" asp-route-id="@property.PropertyId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PROG73020-M3-Group10/Views/Property/GetProperties.cshtml
@using EntityLibrary.Entities;
@model PropertiesViewModel

@{
    ViewData["Title"] = $"Properties List";
}

<a class="btn btn-primary" asp-controller="Property" asp-action="GetMyListings">View My Listings</a>
<br>
<form asp-controller="Property" asp-action="GetProperties" method="post">
    <div class="form-group">
        <label for="search">Search: </label>
        <input type="text" name="search" class="form-control" value="@ViewBag.SearchTerm" />
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>
<br>
<h2>Properties List</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Property Address</th>
            <th>Property City</th>
            <th>Price per Night</th>
            <th>Description</th>
            <th>More Info</th>
        </tr>
    </thead>
    <tbody>
        <!-- iterate thru our list of Properties if they contain the right search term: -->
        @foreach (Property property in Model.AllProperties.Where(p => string.IsNullOrEmpty(ViewBag.SearchTerm) || p.Address.Contains(ViewBag.SearchTerm) || p.City.Contains(ViewBag.SearchTerm) || p.Description.Contains(ViewBag.SearchTerm)))
        {
            <tr>
                <td>@property.Address</td>
                <td>@property.City</td>
                <td>$@property.PricePerNight</td>
                <td>@property.Description</td>
                <td>
                    <a class="btn btn-secondary" asp-controller="Property" asp-action="PropertyDetails" asp-route-Id="@property.PropertyId">View Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PROG73020-M3-Group10/Views/Property/PropertyDetails.cshtml
@using EntityLibrary.Entities;
@model Property

@{
    ViewData["Title"] = "Property";
}

<h1> Property: @Model.Address </h1>

<h3>Address </h3>
<p>Address: @Model.Address</p>
<p>City: @Model.City</p>
<p>State: @Model.ProvinceOrState</p>
<p>PostalCode: @Model.ProvinceOrState</p>
<h3>Property Info </h3>
<p>Description: @Model.Description</p>
<p>Bedrooms: @Model.Bedrooms</p>
<p>Bathrooms: @Model.Bathrooms</p>
<p>Price: $@Model.PricePerNight</p>
<p>Appliances: @Model.Appliances</p>
<h3>Options  </h3>

<div class="btn-group" role="group" aria-label="Profile Options">
    <a class="btn btn-primary" asp-controller="Property" asp-action="BookProperty">Reserve</a>
    <a class="btn btn-primary" asp-controller="Property" asp-action="GetProperties">Return to Listings</a>
</div>